typography_spectrum: 0.01455026981420815
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.19237869838252664
  lightness: 0.39100088737905025
  saturation: 0.6244582871440798
  rhythmicContrast: 0.9533880979288369
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.024914170149713755
analytics:
  google: null
  facebook: null
  twitter: null
name: norm
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Nice one, BRAVUR'
description: I'm being stalked by the Ikea station clock
purpose: []
