name: norm
favicon: null
layout_spectrum: 0.14060888951644301
typography_spectrum: 0.2198877357877791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.890918520046398
  lightness: 0.7495849383994937
  saturation: 0.19134106603451073
  rhythmicContrast: 0.38129751314409077
purpose: []
